export interface Recipe {
  id: number
  title: string
  category: "makanan" | "minuman" | "jajanan"
  author: {
    name: string
    username: string
    location: string
    avatar: string
  }
  description: string
  image: string
  prepTime: string
  cookTime: string
  totalTime: string
  servings: number
  cooksnaps: number
  saves: number
  reactions: {
    hungry: number
    love: number
    applause: number
  }
  ingredients: Array<{
    item: string
    category: string
  }>
  instructions: Array<{
    step: number
    description: string
    images: string[]
  }>
}

export const recipes: Recipe[] = [
  // MASAKAN INDONESIA (20 recipes)
  {
    id: 1,
    title: "Rendang Daging Sapi",
    category: "makanan",
    author: {
      name: "Chef Padang",
      username: "@chefpadang",
      location: "Padang",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Rendang daging sapi khas Minangkabau dengan bumbu rempah yang kaya",
    image: "/rendang-daging-sapi.jpg",
    prepTime: "30 menit",
    cookTime: "3 jam",
    totalTime: "3 jam 30 menit",
    servings: 6,
    cooksnaps: 234,
    saves: 567,
    reactions: {
      hungry: 45,
      love: 89,
      applause: 23,
    },
    ingredients: [
      { item: "1 kg daging sapi, potong dadu", category: "Bahan Utama" },
      { item: "1 liter santan kental", category: "Bahan Utama" },
      { item: "3 lembar daun salam", category: "Bumbu" },
      { item: "3 lembar daun jeruk", category: "Bumbu" },
      { item: "2 batang serai, memarkan", category: "Bumbu" },
      { item: "3 cm lengkuas, memarkan", category: "Bumbu" },
      { item: "10 cabai merah keriting", category: "Bumbu Halus" },
      { item: "8 siung bawang merah", category: "Bumbu Halus" },
      { item: "5 siung bawang putih", category: "Bumbu Halus" },
      { item: "3 cm jahe", category: "Bumbu Halus" },
      { item: "2 cm kunyit", category: "Bumbu Halus" },
      { item: "1 sdm ketumbar", category: "Bumbu Halus" },
      { item: "Garam dan gula secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description:
          "Haluskan semua bumbu halus menggunakan blender atau cobek hingga benar-benar halus dan tercampur rata.",
        images: [],
      },
      {
        step: 2,
        description:
          "Tumis bumbu halus bersama daun salam, daun jeruk, serai, dan lengkuas hingga harum dan matang, sekitar 10 menit.",
        images: [],
      },
      {
        step: 3,
        description: "Masukkan daging sapi, aduk rata dengan bumbu. Masak hingga daging berubah warna.",
        images: [],
      },
      {
        step: 4,
        description: "Tuang santan, masak dengan api sedang sambil terus diaduk agar santan tidak pecah.",
        images: [],
      },
      {
        step: 5,
        description:
          "Kecilkan api, masak sambil sesekali diaduk hingga santan menyusut dan bumbu meresap ke dalam daging, sekitar 3 jam.",
        images: [],
      },
      {
        step: 6,
        description:
          "Rendang siap disajikan saat kuah sudah mengental dan daging empuk. Sajikan dengan nasi putih hangat.",
        images: [],
      },
    ],
  },
  {
    id: 2,
    title: "Soto Ayam Lamongan",
    category: "makanan",
    author: {
      name: "Ibu Soto",
      username: "@ibusoto",
      location: "Lamongan",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Soto ayam khas Lamongan dengan kuah bening yang segar dan gurih",
    image: "/soto-ayam-lamongan.jpg",
    prepTime: "20 menit",
    cookTime: "45 menit",
    totalTime: "1 jam 5 menit",
    servings: 4,
    cooksnaps: 189,
    saves: 423,
    reactions: {
      hungry: 67,
      love: 102,
      applause: 34,
    },
    ingredients: [
      { item: "500 gram daging ayam", category: "Bahan Utama" },
      { item: "2 liter air", category: "Bahan Utama" },
      { item: "100 gram kol, iris tipis", category: "Pelengkap" },
      { item: "2 batang daun bawang, iris", category: "Pelengkap" },
      { item: "3 butir telur rebus", category: "Pelengkap" },
      { item: "100 gram tauge", category: "Pelengkap" },
      { item: "5 siung bawang putih", category: "Bumbu Halus" },
      { item: "3 siung bawang merah", category: "Bumbu Halus" },
      { item: "2 cm kunyit", category: "Bumbu Halus" },
      { item: "1 sdt merica", category: "Bumbu Halus" },
      { item: "3 batang serai, memarkan", category: "Bumbu" },
      { item: "2 lembar daun salam", category: "Bumbu" },
      { item: "Garam dan kaldu ayam secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus ayam dalam air mendidih hingga matang, angkat dan suwir-suwir. Sisihkan kaldu ayam.",
        images: [],
      },
      {
        step: 2,
        description: "Haluskan bawang putih, bawang merah, kunyit, dan merica.",
        images: [],
      },
      {
        step: 3,
        description: "Tumis bumbu halus bersama serai dan daun salam hingga harum.",
        images: [],
      },
      {
        step: 4,
        description:
          "Masukkan bumbu tumis ke dalam kaldu ayam, masak hingga mendidih. Tambahkan garam dan kaldu bubuk.",
        images: [],
      },
      {
        step: 5,
        description: "Siapkan mangkuk saji, masukkan suwiran ayam, kol, tauge, telur rebus, dan daun bawang.",
        images: [],
      },
      {
        step: 6,
        description: "Siram dengan kuah soto panas. Sajikan dengan sambal, kecap, dan jeruk nipis.",
        images: [],
      },
    ],
  },
  {
    id: 3,
    title: "Nasi Goreng Kampung",
    category: "makanan",
    author: {
      name: "Pak Nasgor",
      username: "@paknasgor",
      location: "Jakarta",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Nasi goreng kampung dengan teri dan telur yang gurih dan nikmat",
    image: "/nasi-goreng-kampung.jpg",
    prepTime: "15 menit",
    cookTime: "20 menit",
    totalTime: "35 menit",
    servings: 2,
    cooksnaps: 456,
    saves: 789,
    reactions: {
      hungry: 123,
      love: 234,
      applause: 67,
    },
    ingredients: [
      { item: "2 piring nasi putih", category: "Bahan Utama" },
      { item: "2 butir telur ayam", category: "Bahan Utama" },
      { item: "50 gram teri medan", category: "Bahan Utama" },
      { item: "3 siung bawang putih, cincang", category: "Bumbu" },
      { item: "5 siung bawang merah, iris tipis", category: "Bumbu" },
      { item: "3 cabai rawit merah", category: "Bumbu" },
      { item: "2 sdm kecap manis", category: "Bumbu" },
      { item: "1 sdt terasi bakar", category: "Bumbu" },
      { item: "2 batang daun bawang, iris", category: "Pelengkap" },
      { item: "Garam dan penyedap secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Panaskan minyak, goreng teri hingga kering dan garing. Angkat dan tiriskan.",
        images: [],
      },
      {
        step: 2,
        description: "Kocok telur, buat orak-arik di wajan. Sisihkan ke pinggir wajan.",
        images: [],
      },
      {
        step: 3,
        description: "Tumis bawang putih, bawang merah, dan cabai rawit hingga harum.",
        images: [],
      },
      {
        step: 4,
        description: "Masukkan terasi, aduk rata. Tambahkan nasi putih, aduk hingga bumbu merata.",
        images: [],
      },
      {
        step: 5,
        description: "Tuang kecap manis, tambahkan teri goreng dan daun bawang. Aduk rata.",
        images: [],
      },
      {
        step: 6,
        description:
          "Beri garam dan penyedap sesuai selera. Masak hingga nasi panas merata. Sajikan dengan kerupuk dan acar.",
        images: [],
      },
    ],
  },
  {
    id: 4,
    title: "Gado-Gado Jakarta",
    category: "makanan",
    author: {
      name: "Mak Gado",
      username: "@makgado",
      location: "Jakarta",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Gado-gado dengan bumbu kacang yang kental dan sayuran segar",
    image: "/gado-gado-jakarta.jpg",
    prepTime: "25 menit",
    cookTime: "20 menit",
    totalTime: "45 menit",
    servings: 4,
    cooksnaps: 198,
    saves: 345,
    reactions: {
      hungry: 78,
      love: 145,
      applause: 56,
    },
    ingredients: [
      { item: "100 gram kacang panjang", category: "Sayuran" },
      { item: "100 gram tauge", category: "Sayuran" },
      { item: "100 gram kol", category: "Sayuran" },
      { item: "2 buah kentang, rebus", category: "Sayuran" },
      { item: "2 butir telur rebus", category: "Pelengkap" },
      { item: "2 lembar lontong, potong-potong", category: "Pelengkap" },
      { item: "200 gram kacang tanah goreng", category: "Bumbu Kacang" },
      { item: "3 siung bawang putih goreng", category: "Bumbu Kacang" },
      { item: "5 cabai rawit merah", category: "Bumbu Kacang" },
      { item: "2 sdm gula merah sisir", category: "Bumbu Kacang" },
      { item: "1 sdt terasi bakar", category: "Bumbu Kacang" },
      { item: "Air asam jawa secukupnya", category: "Bumbu Kacang" },
      { item: "Garam secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus semua sayuran satu per satu hingga matang. Tiriskan.",
        images: [],
      },
      {
        step: 2,
        description: "Haluskan kacang tanah goreng, bawang putih, cabai rawit, gula merah, dan terasi.",
        images: [],
      },
      {
        step: 3,
        description: "Tambahkan air secukupnya pada bumbu halus, masak hingga mendidih sambil diaduk.",
        images: [],
      },
      {
        step: 4,
        description: "Tambahkan air asam jawa dan garam, koreksi rasa. Masak hingga bumbu kacang mengental.",
        images: [],
      },
      {
        step: 5,
        description: "Tata sayuran rebus, kentang, telur, dan lontong di piring saji.",
        images: [],
      },
      {
        step: 6,
        description: "Siram dengan bumbu kacang. Sajikan dengan kerupuk dan emping.",
        images: [],
      },
    ],
  },
  {
    id: 5,
    title: "Ayam Geprek Sambal Bawang",
    category: "makanan",
    author: {
      name: "Mas Geprek",
      username: "@masgeprek",
      location: "Yogyakarta",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Ayam goreng crispy yang digeprek dengan sambal bawang pedas",
    image: "/ayam-geprek-sambal-bawang.jpg",
    prepTime: "30 menit",
    cookTime: "30 menit",
    totalTime: "1 jam",
    servings: 3,
    cooksnaps: 567,
    saves: 891,
    reactions: {
      hungry: 234,
      love: 345,
      applause: 123,
    },
    ingredients: [
      { item: "3 potong paha ayam", category: "Bahan Utama" },
      { item: "200 ml air", category: "Bahan Utama" },
      { item: "5 siung bawang putih, haluskan", category: "Marinasi" },
      { item: "1 sdt ketumbar bubuk", category: "Marinasi" },
      { item: "Garam dan penyedap secukupnya", category: "Marinasi" },
      { item: "100 gram tepung terigu", category: "Pelapis" },
      { item: "50 gram tepung maizena", category: "Pelapis" },
      { item: "15 cabai rawit merah", category: "Sambal" },
      { item: "8 siung bawang putih", category: "Sambal" },
      { item: "3 lembar daun jeruk", category: "Sambal" },
      { item: "Garam dan gula secukupnya", category: "Sambal" },
    ],
    instructions: [
      {
        step: 1,
        description:
          "Lumuri ayam dengan bumbu marinasi (bawang putih, ketumbar, garam, penyedap) dan air. Diamkan 30 menit.",
        images: [],
      },
      {
        step: 2,
        description:
          "Campurkan tepung terigu dan maizena. Gulingkan ayam yang sudah dimarinasi ke dalam tepung hingga rata.",
        images: [],
      },
      {
        step: 3,
        description: "Goreng ayam dengan api sedang hingga matang dan berwarna keemasan. Angkat dan tiriskan.",
        images: [],
      },
      {
        step: 4,
        description: "Goreng cabai rawit dan bawang putih hingga setengah layu. Angkat dan ulek kasar.",
        images: [],
      },
      {
        step: 5,
        description: "Tumis sambal ulek bersama daun jeruk iris halus. Tambahkan garam dan gula, masak sebentar.",
        images: [],
      },
      {
        step: 6,
        description: "Geprek ayam goreng menggunakan ulekan. Siram dengan sambal bawang. Sajikan dengan nasi hangat.",
        images: [],
      },
    ],
  },
  {
    id: 6,
    title: "Sate Ayam Madura",
    category: "makanan",
    author: {
      name: "Pak Sate",
      username: "@paksate",
      location: "Madura",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Sate ayam khas Madura dengan bumbu kacang yang kental dan manis",
    image: "/sate-ayam-madura.jpg",
    prepTime: "40 menit",
    cookTime: "25 menit",
    totalTime: "1 jam 5 menit",
    servings: 4,
    cooksnaps: 312,
    saves: 567,
    reactions: {
      hungry: 145,
      love: 198,
      applause: 89,
    },
    ingredients: [
      { item: "500 gram daging ayam fillet, potong dadu", category: "Bahan Utama" },
      { item: "3 sdm kecap manis", category: "Marinasi" },
      { item: "2 sdm air jeruk nipis", category: "Marinasi" },
      { item: "Garam secukupnya", category: "Marinasi" },
      { item: "Tusuk sate secukupnya", category: "Pelengkap" },
      { item: "200 gram kacang tanah goreng", category: "Bumbu Kacang" },
      { item: "5 siung bawang putih", category: "Bumbu Kacang" },
      { item: "5 cabai rawit merah", category: "Bumbu Kacang" },
      { item: "3 sdm kecap manis", category: "Bumbu Kacang" },
      { item: "1 sdm gula merah", category: "Bumbu Kacang" },
      { item: "Air secukupnya", category: "Bumbu Kacang" },
    ],
    instructions: [
      {
        step: 1,
        description: "Marinasi daging ayam dengan kecap manis, air jeruk nipis, dan garam. Diamkan 30 menit.",
        images: [],
      },
      {
        step: 2,
        description: "Tusuk daging ayam dengan tusuk sate, sisihkan.",
        images: [],
      },
      {
        step: 3,
        description: "Haluskan kacang tanah, bawang putih, dan cabai rawit. Tambahkan air secukupnya.",
        images: [],
      },
      {
        step: 4,
        description: "Masak bumbu kacang dengan kecap manis dan gula merah hingga mendidih dan mengental.",
        images: [],
      },
      {
        step: 5,
        description: "Bakar sate ayam sambil dioles dengan sisa marinasi hingga matang dan sedikit kecokelatan.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan sate panas dengan bumbu kacang, lontong, dan bawang merah goreng.",
        images: [],
      },
    ],
  },
  {
    id: 7,
    title: "Rawon Daging Sapi",
    category: "makanan",
    author: {
      name: "Bu Rawon",
      username: "@burawon",
      location: "Surabaya",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Rawon khas Jawa Timur dengan kuah hitam yang kaya rempah",
    image: "/rawon-daging-sapi.jpg",
    prepTime: "25 menit",
    cookTime: "2 jam",
    totalTime: "2 jam 25 menit",
    servings: 6,
    cooksnaps: 234,
    saves: 456,
    reactions: {
      hungry: 112,
      love: 167,
      applause: 78,
    },
    ingredients: [
      { item: "500 gram daging sapi, potong dadu", category: "Bahan Utama" },
      { item: "1.5 liter air", category: "Bahan Utama" },
      { item: "3 buah kluwek", category: "Bumbu Halus" },
      { item: "6 siung bawang putih", category: "Bumbu Halus" },
      { item: "8 siung bawang merah", category: "Bumbu Halus" },
      { item: "5 cabai merah keriting", category: "Bumbu Halus" },
      { item: "3 cm lengkuas", category: "Bumbu Halus" },
      { item: "2 cm jahe", category: "Bumbu Halus" },
      { item: "1 sdt ketumbar", category: "Bumbu Halus" },
      { item: "3 lembar daun salam", category: "Bumbu" },
      { item: "2 batang serai, memarkan", category: "Bumbu" },
      { item: "Garam dan penyedap secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Keluarkan isi kluwek, buang seratnya. Haluskan bersama bumbu halus lainnya.",
        images: [],
      },
      {
        step: 2,
        description: "Rebus daging sapi dalam air hingga empuk, sekitar 1.5 jam. Sisihkan kaldu.",
        images: [],
      },
      {
        step: 3,
        description: "Tumis bumbu halus bersama daun salam dan serai hingga harum dan matang.",
        images: [],
      },
      {
        step: 4,
        description: "Masukkan bumbu tumis ke dalam kaldu daging, masak hingga mendidih.",
        images: [],
      },
      {
        step: 5,
        description: "Tambahkan garam dan penyedap, masak hingga bumbu meresap, sekitar 30 menit.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan rawon panas dengan nasi, tauge, telur asin, sambal, dan kerupuk.",
        images: [],
      },
    ],
  },
  {
    id: 8,
    title: "Pecel Lele Lamongan",
    category: "makanan",
    author: {
      name: "Mas Lele",
      username: "@maslele",
      location: "Lamongan",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Lele goreng crispy dengan sambal terasi dan lalapan segar",
    image: "/pecel-lele-lamongan.jpg",
    prepTime: "20 menit",
    cookTime: "20 menit",
    totalTime: "40 menit",
    servings: 3,
    cooksnaps: 423,
    saves: 678,
    reactions: {
      hungry: 198,
      love: 267,
      applause: 134,
    },
    ingredients: [
      { item: "3 ekor ikan lele, bersihkan", category: "Bahan Utama" },
      { item: "2 siung bawang putih, haluskan", category: "Marinasi" },
      { item: "1 sdt ketumbar bubuk", category: "Marinasi" },
      { item: "Garam secukupnya", category: "Marinasi" },
      { item: "Air jeruk nipis secukupnya", category: "Marinasi" },
      { item: "15 cabai rawit merah", category: "Sambal" },
      { item: "5 cabai merah keriting", category: "Sambal" },
      { item: "4 siung bawang merah", category: "Sambal" },
      { item: "2 siung bawang putih", category: "Sambal" },
      { item: "1 sdt terasi bakar", category: "Sambal" },
      { item: "Tomat dan mentimun untuk lalapan", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description:
          "Lumuri ikan lele dengan bawang putih halus, ketumbar, garam, dan air jeruk nipis. Diamkan 15 menit.",
        images: [],
      },
      {
        step: 2,
        description: "Goreng ikan lele dengan api sedang hingga matang dan crispy. Angkat dan tiriskan.",
        images: [],
      },
      {
        step: 3,
        description: "Goreng semua bahan sambal (cabai, bawang merah, bawang putih) hingga layu.",
        images: [],
      },
      {
        step: 4,
        description:
          "Ulek semua bahan sambal yang sudah digoreng bersama terasi hingga halus atau kasar sesuai selera.",
        images: [],
      },
      {
        step: 5,
        description: "Tambahkan sedikit garam dan gula pada sambal, aduk rata.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan lele goreng dengan sambal terasi, lalapan, dan nasi hangat.",
        images: [],
      },
    ],
  },
  {
    id: 9,
    title: "Bakso Sapi Kenyal",
    category: "makanan",
    author: {
      name: "Bang Bakso",
      username: "@bangbakso",
      location: "Malang",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Bakso sapi kenyal dengan kuah kaldu yang gurih dan segar",
    image: "/bakso-sapi-kenyal.jpg",
    prepTime: "40 menit",
    cookTime: "45 menit",
    totalTime: "1 jam 25 menit",
    servings: 6,
    cooksnaps: 345,
    saves: 678,
    reactions: {
      hungry: 167,
      love: 234,
      applause: 98,
    },
    ingredients: [
      { item: "500 gram daging sapi giling", category: "Bakso" },
      { item: "100 gram es batu", category: "Bakso" },
      { item: "5 siung bawang putih", category: "Bakso" },
      { item: "1 butir telur", category: "Bakso" },
      { item: "100 gram tepung tapioka", category: "Bakso" },
      { item: "Garam dan penyedap secukupnya", category: "Bakso" },
      { item: "500 gram tulang sapi", category: "Kuah" },
      { item: "2 liter air", category: "Kuah" },
      { item: "3 siung bawang putih, goreng", category: "Kuah" },
      { item: "Daun bawang dan seledri", category: "Pelengkap" },
      { item: "Mie kuning secukupnya", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus tulang sapi dalam air hingga mendidih dan kaldu keluar. Buang kotoran yang mengapung.",
        images: [],
      },
      {
        step: 2,
        description: "Haluskan daging sapi giling, es batu, bawang putih, dan telur menggunakan food processor.",
        images: [],
      },
      {
        step: 3,
        description: "Campurkan adonan daging dengan tepung tapioka, garam, dan penyedap. Uleni hingga kalis.",
        images: [],
      },
      {
        step: 4,
        description: "Bentuk adonan menjadi bulatan bakso. Rebus dalam air mendidih hingga bakso mengapung.",
        images: [],
      },
      {
        step: 5,
        description: "Tambahkan bawang putih goreng ke dalam kaldu. Beri garam dan penyedap, koreksi rasa.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan bakso dengan mie, kuah kaldu panas, daun bawang, seledri, dan sambal.",
        images: [],
      },
    ],
  },
  {
    id: 10,
    title: "Gudeg Jogja",
    category: "makanan",
    author: {
      name: "Yu Gudeg",
      username: "@yugudeg",
      location: "Yogyakarta",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Gudeg khas Yogyakarta dengan nangka muda yang manis dan gurih",
    image: "/gudeg-jogja.jpg",
    prepTime: "30 menit",
    cookTime: "4 jam",
    totalTime: "4 jam 30 menit",
    servings: 6,
    cooksnaps: 278,
    saves: 512,
    reactions: {
      hungry: 134,
      love: 189,
      applause: 87,
    },
    ingredients: [
      { item: "1 kg nangka muda, potong-potong", category: "Bahan Utama" },
      { item: "500 ml santan kental", category: "Bahan Utama" },
      { item: "3 lembar daun salam", category: "Bumbu" },
      { item: "2 lembar daun jati (opsional)", category: "Bumbu" },
      { item: "3 cm lengkuas, memarkan", category: "Bumbu" },
      { item: "150 gram gula merah", category: "Bumbu" },
      { item: "5 siung bawang putih", category: "Bumbu Halus" },
      { item: "8 siung bawang merah", category: "Bumbu Halus" },
      { item: "5 butir kemiri", category: "Bumbu Halus" },
      { item: "1 sdt ketumbar", category: "Bumbu Halus" },
      { item: "Garam secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus nangka muda hingga setengah lunak, tiriskan.",
        images: [],
      },
      {
        step: 2,
        description: "Haluskan semua bumbu halus.",
        images: [],
      },
      {
        step: 3,
        description: "Masak nangka dengan bumbu halus, daun salam, daun jati, lengkuas, dan santan dengan api kecil.",
        images: [],
      },
      {
        step: 4,
        description:
          "Tambahkan gula merah dan garam. Masak sambil sesekali diaduk hingga bumbu meresap dan santan menyusut, sekitar 4 jam.",
        images: [],
      },
      {
        step: 5,
        description: "Gudeg siap saat nangka berubah warna kecokelatan dan empuk.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan gudeg dengan nasi, ayam kampung, telur, krecek, dan sambal krecek.",
        images: [],
      },
    ],
  },
  {
    id: 11,
    title: "Pempek Palembang",
    category: "makanan",
    author: {
      name: "Cik Pempek",
      username: "@cikpempek",
      location: "Palembang",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Pempek ikan tenggiri dengan cuko yang asam manis pedas",
    image: "/pempek-palembang.jpg",
    prepTime: "45 menit",
    cookTime: "30 menit",
    totalTime: "1 jam 15 menit",
    servings: 8,
    cooksnaps: 389,
    saves: 634,
    reactions: {
      hungry: 178,
      love: 245,
      applause: 112,
    },
    ingredients: [
      { item: "500 gram ikan tenggiri, haluskan", category: "Bahan Utama" },
      { item: "250 gram tepung tapioka", category: "Bahan Utama" },
      { item: "200 ml air es", category: "Bahan Utama" },
      { item: "3 siung bawang putih, haluskan", category: "Bahan Utama" },
      { item: "1 butir telur", category: "Bahan Utama" },
      { item: "Garam secukupnya", category: "Penyedap" },
      { item: "200 gram gula merah", category: "Cuko" },
      { item: "100 ml air asam jawa", category: "Cuko" },
      { item: "10 cabai rawit", category: "Cuko" },
      { item: "5 siung bawang putih", category: "Cuko" },
      { item: "Garam secukupnya", category: "Cuko" },
    ],
    instructions: [
      {
        step: 1,
        description: "Campurkan ikan tenggiri halus dengan bawang putih, telur, dan garam. Aduk rata.",
        images: [],
      },
      {
        step: 2,
        description: "Tambahkan tepung tapioka sedikit demi sedikit, uleni sambil dituang air es hingga adonan kalis.",
        images: [],
      },
      {
        step: 3,
        description: "Bentuk adonan menjadi pempek lenjer atau kapal selam. Rebus dalam air mendidih hingga mengapung.",
        images: [],
      },
      {
        step: 4,
        description: "Angkat pempek, tiriskan. Goreng sebentar hingga permukaan sedikit kering.",
        images: [],
      },
      {
        step: 5,
        description:
          "Untuk cuko: rebus gula merah dengan air hingga larut. Tambahkan air asam jawa, cabai, bawang putih halus, dan garam.",
        images: [],
      },
      {
        step: 6,
        description: "Potong-potong pempek, sajikan dengan cuko, mentimun, dan mie kuning.",
        images: [],
      },
    ],
  },
  {
    id: 12,
    title: "Opor Ayam Kampung",
    category: "makanan",
    author: {
      name: "Ibu Opor",
      username: "@ibuopor",
      location: "Solo",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Opor ayam dengan kuah santan yang gurih dan creamy",
    image: "/opor-ayam-kampung.jpg",
    prepTime: "20 menit",
    cookTime: "50 menit",
    totalTime: "1 jam 10 menit",
    servings: 5,
    cooksnaps: 267,
    saves: 489,
    reactions: {
      hungry: 145,
      love: 198,
      applause: 89,
    },
    ingredients: [
      { item: "1 ekor ayam kampung, potong 12 bagian", category: "Bahan Utama" },
      { item: "800 ml santan dari 1 butir kelapa", category: "Bahan Utama" },
      { item: "3 lembar daun salam", category: "Bumbu" },
      { item: "2 batang serai, memarkan", category: "Bumbu" },
      { item: "3 cm lengkuas, memarkan", category: "Bumbu" },
      { item: "8 siung bawang putih", category: "Bumbu Halus" },
      { item: "10 siung bawang merah", category: "Bumbu Halus" },
      { item: "5 butir kemiri", category: "Bumbu Halus" },
      { item: "2 cm jahe", category: "Bumbu Halus" },
      { item: "1 sdt ketumbar", category: "Bumbu Halus" },
      { item: "1/2 sdt merica", category: "Bumbu Halus" },
      { item: "Garam dan gula secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Haluskan semua bumbu halus.",
        images: [],
      },
      {
        step: 2,
        description: "Tumis bumbu halus bersama daun salam, serai, dan lengkuas hingga harum.",
        images: [],
      },
      {
        step: 3,
        description: "Masukkan ayam, aduk hingga ayam berubah warna.",
        images: [],
      },
      {
        step: 4,
        description: "Tuang santan, masak dengan api sedang sambil terus diaduk agar santan tidak pecah.",
        images: [],
      },
      {
        step: 5,
        description: "Tambahkan garam dan gula, masak hingga ayam empuk dan kuah mengental, sekitar 40 menit.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan opor ayam hangat dengan nasi putih dan sambal.",
        images: [],
      },
    ],
  },
  {
    id: 13,
    title: "Mie Aceh Pedas",
    category: "makanan",
    author: {
      name: "Abang Mie",
      username: "@abangmie",
      location: "Banda Aceh",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Mie Aceh dengan bumbu rempah yang kaya dan pedas menggugah selera",
    image: "/mie-aceh-pedas.jpg",
    prepTime: "25 menit",
    cookTime: "30 menit",
    totalTime: "55 menit",
    servings: 3,
    cooksnaps: 412,
    saves: 723,
    reactions: {
      hungry: 189,
      love: 278,
      applause: 134,
    },
    ingredients: [
      { item: "300 gram mie kuning segar", category: "Bahan Utama" },
      { item: "200 gram daging sapi, iris tipis", category: "Bahan Utama" },
      { item: "100 gram udang, kupas", category: "Bahan Utama" },
      { item: "100 gram kol, iris kasar", category: "Sayuran" },
      { item: "50 gram tauge", category: "Sayuran" },
      { item: "2 batang daun bawang, iris", category: "Sayuran" },
      { item: "6 siung bawang merah", category: "Bumbu Halus" },
      { item: "4 siung bawang putih", category: "Bumbu Halus" },
      { item: "5 cabai merah keriting", category: "Bumbu Halus" },
      { item: "3 cabai rawit", category: "Bumbu Halus" },
      { item: "1 sdt jintan", category: "Bumbu Halus" },
      { item: "1 sdt ketumbar", category: "Bumbu Halus" },
      { item: "2 sdm kecap manis", category: "Bumbu" },
      { item: "Garam dan penyedap secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus mie kuning hingga matang, tiriskan dan sisihkan.",
        images: [],
      },
      {
        step: 2,
        description: "Haluskan semua bumbu halus.",
        images: [],
      },
      {
        step: 3,
        description: "Tumis bumbu halus hingga harum. Masukkan daging sapi dan udang, masak hingga berubah warna.",
        images: [],
      },
      {
        step: 4,
        description: "Masukkan kol dan tauge, aduk sebentar.",
        images: [],
      },
      {
        step: 5,
        description: "Masukkan mie, kecap manis, garam, dan penyedap. Aduk rata dengan api besar.",
        images: [],
      },
      {
        step: 6,
        description:
          "Tambahkan daun bawang, aduk sebentar. Sajikan mie Aceh panas dengan emping, bawang goreng, dan jeruk nipis.",
        images: [],
      },
    ],
  },
  {
    id: 14,
    title: "Ikan Bakar Kecap",
    category: "makanan",
    author: {
      name: "Mas Bakar",
      username: "@masbakar",
      location: "Bali",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Ikan bakar dengan bumbu kecap manis yang gurih dan sedikit manis",
    image: "/ikan-bakar-kecap.jpg",
    prepTime: "30 menit",
    cookTime: "25 menit",
    totalTime: "55 menit",
    servings: 3,
    cooksnaps: 334,
    saves: 556,
    reactions: {
      hungry: 156,
      love: 212,
      applause: 98,
    },
    ingredients: [
      { item: "3 ekor ikan bandeng atau kembung", category: "Bahan Utama" },
      { item: "5 sdm kecap manis", category: "Bumbu" },
      { item: "2 sdm air jeruk nipis", category: "Bumbu" },
      { item: "3 sdm margarin, lelehkan", category: "Bumbu" },
      { item: "5 siung bawang putih, haluskan", category: "Bumbu Halus" },
      { item: "3 siung bawang merah, haluskan", category: "Bumbu Halus" },
      { item: "5 cabai rawit merah", category: "Bumbu Halus" },
      { item: "1 cm jahe", category: "Bumbu Halus" },
      { item: "Garam secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Bersihkan ikan, beri irisan pada bagian daging agar bumbu meresap.",
        images: [],
      },
      {
        step: 2,
        description: "Haluskan bawang putih, bawang merah, cabai rawit, dan jahe.",
        images: [],
      },
      {
        step: 3,
        description: "Campurkan bumbu halus dengan kecap manis, air jeruk nipis, margarin leleh, dan garam.",
        images: [],
      },
      {
        step: 4,
        description: "Lumuri ikan dengan bumbu kecap hingga rata. Diamkan 20 menit.",
        images: [],
      },
      {
        step: 5,
        description: "Bakar ikan sambil dioles sisa bumbu hingga matang dan sedikit gosong.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan ikan bakar panas dengan nasi, sambal, dan lalapan.",
        images: [],
      },
    ],
  },
  {
    id: 15,
    title: "Gulai Kambing",
    category: "makanan",
    author: {
      name: "Pak Gulai",
      username: "@pakgulai",
      location: "Medan",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Gulai kambing dengan kuah santan yang kental dan gurih",
    image: "/gulai-kambing.jpg",
    prepTime: "25 menit",
    cookTime: "1 jam 30 menit",
    totalTime: "1 jam 55 menit",
    servings: 6,
    cooksnaps: 298,
    saves: 512,
    reactions: {
      hungry: 167,
      love: 223,
      applause: 104,
    },
    ingredients: [
      { item: "750 gram daging kambing, potong dadu", category: "Bahan Utama" },
      { item: "800 ml santan kental", category: "Bahan Utama" },
      { item: "3 lembar daun salam", category: "Bumbu" },
      { item: "2 lembar daun jeruk", category: "Bumbu" },
      { item: "2 batang serai, memarkan", category: "Bumbu" },
      { item: "3 cm lengkuas, memarkan", category: "Bumbu" },
      { item: "8 siung bawang merah", category: "Bumbu Halus" },
      { item: "5 siung bawang putih", category: "Bumbu Halus" },
      { item: "5 cabai merah keriting", category: "Bumbu Halus" },
      { item: "3 cm jahe", category: "Bumbu Halus" },
      { item: "2 cm kunyit", category: "Bumbu Halus" },
      { item: "1 sdm ketumbar", category: "Bumbu Halus" },
      { item: "1 sdt jintan", category: "Bumbu Halus" },
      { item: "Garam dan gula secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description:
          "Rebus daging kambing dalam air mendidih sebentar, buang air rebusan untuk menghilangkan bau. Tiriskan.",
        images: [],
      },
      {
        step: 2,
        description: "Haluskan semua bumbu halus.",
        images: [],
      },
      {
        step: 3,
        description: "Tumis bumbu halus bersama daun salam, daun jeruk, serai, dan lengkuas hingga harum.",
        images: [],
      },
      {
        step: 4,
        description: "Masukkan daging kambing, aduk hingga daging berubah warna.",
        images: [],
      },
      {
        step: 5,
        description: "Tuang santan, masak dengan api sedang hingga daging empuk dan kuah mengental, sekitar 1.5 jam.",
        images: [],
      },
      {
        step: 6,
        description: "Tambahkan garam dan gula, koreksi rasa. Sajikan gulai panas dengan nasi atau ketupat.",
        images: [],
      },
    ],
  },
  {
    id: 16,
    title: "Perkedel Kentang",
    category: "makanan",
    author: {
      name: "Ibu Kedel",
      username: "@ibukedel",
      location: "Bandung",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Perkedel kentang yang renyah di luar dan lembut di dalam",
    image: "/perkedel-kentang.jpg",
    prepTime: "30 menit",
    cookTime: "30 menit",
    totalTime: "1 jam",
    servings: 15,
    cooksnaps: 445,
    saves: 778,
    reactions: {
      hungry: 212,
      love: 334,
      applause: 156,
    },
    ingredients: [
      { item: "500 gram kentang, kupas", category: "Bahan Utama" },
      { item: "100 gram daging sapi cincang", category: "Bahan Utama" },
      { item: "2 batang daun bawang, iris halus", category: "Bahan Utama" },
      { item: "2 batang seledri, iris halus", category: "Bahan Utama" },
      { item: "3 siung bawang putih, haluskan", category: "Bumbu" },
      { item: "5 siung bawang merah, haluskan", category: "Bumbu" },
      { item: "1 sdt merica bubuk", category: "Bumbu" },
      { item: "1 sdt pala bubuk", category: "Bumbu" },
      { item: "2 butir telur", category: "Pelengkap" },
      { item: "Garam dan penyedap secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus kentang hingga empuk. Angkat, tiriskan, dan haluskan selagi panas.",
        images: [],
      },
      {
        step: 2,
        description: "Tumis bawang merah dan bawang putih hingga harum. Masukkan daging cincang, masak hingga matang.",
        images: [],
      },
      {
        step: 3,
        description:
          "Campurkan kentang halus dengan tumisan daging, daun bawang, seledri, merica, pala, garam, dan penyedap.",
        images: [],
      },
      {
        step: 4,
        description: "Bentuk adonan menjadi bulatan pipih. Celupkan ke dalam telur kocok.",
        images: [],
      },
      {
        step: 5,
        description: "Goreng perkedel dengan api sedang hingga kedua sisi berwarna keemasan.",
        images: [],
      },
      {
        step: 6,
        description: "Angkat dan tiriskan. Sajikan perkedel hangat sebagai lauk atau camilan.",
        images: [],
      },
    ],
  },
  {
    id: 17,
    title: "Capcay Kuah",
    category: "makanan",
    author: {
      name: "Ko Capcay",
      username: "@kocapcay",
      location: "Jakarta",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Capcay kuah dengan aneka sayuran segar dan kuah yang gurih",
    image: "/capcay-kuah.jpg",
    prepTime: "20 menit",
    cookTime: "20 menit",
    totalTime: "40 menit",
    servings: 4,
    cooksnaps: 267,
    saves: 445,
    reactions: {
      hungry: 134,
      love: 189,
      applause: 87,
    },
    ingredients: [
      { item: "100 gram bakso sapi, iris", category: "Protein" },
      { item: "100 gram udang, kupas", category: "Protein" },
      { item: "100 gram wortel, potong serong", category: "Sayuran" },
      { item: "100 gram brokoli", category: "Sayuran" },
      { item: "100 gram kembang kol", category: "Sayuran" },
      { item: "100 gram sawi putih, potong", category: "Sayuran" },
      { item: "50 gram jamur kuping", category: "Sayuran" },
      { item: "3 siung bawang putih, cincang", category: "Bumbu" },
      { item: "1 buah bawang bombay, potong", category: "Bumbu" },
      { item: "500 ml air kaldu", category: "Kuah" },
      { item: "2 sdm saus tiram", category: "Bumbu" },
      { item: "1 sdm kecap asin", category: "Bumbu" },
      { item: "1 sdm maizena, larutkan", category: "Pengental" },
      { item: "Garam, gula, merica secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Tumis bawang putih dan bawang bombay hingga harum.",
        images: [],
      },
      {
        step: 2,
        description: "Masukkan udang dan bakso, tumis sebentar.",
        images: [],
      },
      {
        step: 3,
        description: "Tuang air kaldu, masukkan wortel. Masak hingga wortel setengah lunak.",
        images: [],
      },
      {
        step: 4,
        description:
          "Masukkan brokoli, kembang kol, jamur kuping, dan sawi putih. Masak sebentar agar sayuran tetap renyah.",
        images: [],
      },
      {
        step: 5,
        description:
          "Tambahkan saus tiram, kecap asin, garam, gula, dan merica. Tuang larutan maizena, aduk hingga kuah mengental.",
        images: [],
      },
      {
        step: 6,
        description: "Koreksi rasa. Sajikan capcay kuah panas dengan nasi putih.",
        images: [],
      },
    ],
  },
  {
    id: 18,
    title: "Ayam Taliwang",
    category: "makanan",
    author: {
      name: "Mas Taliwang",
      username: "@mastaliwang",
      location: "Lombok",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Ayam bakar khas Lombok dengan sambal yang pedas dan gurih",
    image: "/ayam-taliwang.jpg",
    prepTime: "35 menit",
    cookTime: "40 menit",
    totalTime: "1 jam 15 menit",
    servings: 3,
    cooksnaps: 378,
    saves: 623,
    reactions: {
      hungry: 189,
      love: 256,
      applause: 123,
    },
    ingredients: [
      { item: "1 ekor ayam kampung, belah dua", category: "Bahan Utama" },
      { item: "3 sdm air jeruk nipis", category: "Marinasi" },
      { item: "Garam secukupnya", category: "Marinasi" },
      { item: "10 cabai merah keriting", category: "Bumbu" },
      { item: "8 cabai rawit merah", category: "Bumbu" },
      { item: "6 siung bawang merah", category: "Bumbu" },
      { item: "4 siung bawang putih", category: "Bumbu" },
      { item: "3 buah tomat merah", category: "Bumbu" },
      { item: "1 sdt terasi bakar", category: "Bumbu" },
      { item: "2 cm kencur", category: "Bumbu" },
      { item: "2 sdm gula merah sisir", category: "Bumbu" },
      { item: "3 sdm margarin", category: "Bumbu" },
      { item: "Garam secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Lumuri ayam dengan air jeruk nipis dan garam. Diamkan 20 menit.",
        images: [],
      },
      {
        step: 2,
        description: "Bakar cabai, bawang merah, bawang putih, dan tomat hingga harum dan sedikit gosong.",
        images: [],
      },
      {
        step: 3,
        description: "Ulek semua bahan yang sudah dibakar bersama terasi, kencur, dan gula merah hingga halus.",
        images: [],
      },
      {
        step: 4,
        description: "Panaskan margarin, tumis bumbu ulek hingga matang dan berminyak. Tambahkan garam.",
        images: [],
      },
      {
        step: 5,
        description: "Bakar ayam sambil dioles dengan bumbu taliwang hingga matang dan sedikit gosong.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan ayam taliwang panas dengan sisa sambal, plecing kangkung, dan nasi putih.",
        images: [],
      },
    ],
  },
  {
    id: 19,
    title: "Sop Buntut",
    category: "makanan",
    author: {
      name: "Pak Buntut",
      username: "@pakbuntut",
      location: "Jakarta",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Sop buntut sapi dengan kuah kaldu yang gurih dan daging yang empuk",
    image: "/sop-buntut.jpg",
    prepTime: "25 menit",
    cookTime: "3 jam",
    totalTime: "3 jam 25 menit",
    servings: 5,
    cooksnaps: 234,
    saves: 467,
    reactions: {
      hungry: 145,
      love: 201,
      applause: 98,
    },
    ingredients: [
      { item: "1 kg buntut sapi, potong-potong", category: "Bahan Utama" },
      { item: "2.5 liter air", category: "Bahan Utama" },
      { item: "2 buah wortel, potong bulat", category: "Sayuran" },
      { item: "2 buah kentang, potong dadu", category: "Sayuran" },
      { item: "1 batang daun bawang, iris", category: "Sayuran" },
      { item: "2 batang seledri, iris", category: "Sayuran" },
      { item: "5 siung bawang putih, cincang", category: "Bumbu" },
      { item: "3 siung bawang merah, cincang", category: "Bumbu" },
      { item: "2 cm jahe, memarkan", category: "Bumbu" },
      { item: "1 batang serai, memarkan", category: "Bumbu" },
      { item: "3 butir cengkeh", category: "Bumbu" },
      { item: "1 sdt merica bubuk", category: "Bumbu" },
      { item: "1 buah pala utuh", category: "Bumbu" },
      { item: "Garam dan penyedap secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus buntut sapi dalam air mendidih, buang air rebusan pertama untuk menghilangkan bau.",
        images: [],
      },
      {
        step: 2,
        description:
          "Rebus kembali buntut dengan air bersih bersama jahe, serai, cengkeh, dan pala hingga daging empuk, sekitar 2.5-3 jam.",
        images: [],
      },
      {
        step: 3,
        description: "Tumis bawang putih dan bawang merah hingga harum.",
        images: [],
      },
      {
        step: 4,
        description:
          "Masukkan tumisan bawang ke dalam kaldu buntut. Tambahkan wortel dan kentang, masak hingga sayuran empuk.",
        images: [],
      },
      {
        step: 5,
        description: "Beri garam, merica, dan penyedap. Koreksi rasa.",
        images: [],
      },
      {
        step: 6,
        description:
          "Tambahkan daun bawang dan seledri. Sajikan sop buntut panas dengan nasi putih, emping, dan sambal.",
        images: [],
      },
    ],
  },
  {
    id: 20,
    title: "Tahu Gejrot Cirebon",
    category: "makanan",
    author: {
      name: "Bang Gejrot",
      username: "@banggejrot",
      location: "Cirebon",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Tahu goreng dengan kuah asam manis pedas khas Cirebon",
    image: "/tahu-gejrot-cirebon.jpg",
    prepTime: "15 menit",
    cookTime: "15 menit",
    totalTime: "30 menit",
    servings: 3,
    cooksnaps: 512,
    saves: 845,
    reactions: {
      hungry: 267,
      love: 389,
      applause: 178,
    },
    ingredients: [
      { item: "10 buah tahu putih, potong dadu", category: "Bahan Utama" },
      { item: "10 cabai rawit merah", category: "Kuah" },
      { item: "3 siung bawang putih", category: "Kuah" },
      { item: "100 gram gula merah sisir", category: "Kuah" },
      { item: "3 sdm air asam jawa", category: "Kuah" },
      { item: "150 ml air", category: "Kuah" },
      { item: "1 sdt kecap manis", category: "Kuah" },
      { item: "Garam secukupnya", category: "Penyedap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Goreng tahu hingga kecokelatan dan crispy di luar. Angkat dan tiriskan.",
        images: [],
      },
      {
        step: 2,
        description: "Ulek cabai rawit dan bawang putih hingga kasar.",
        images: [],
      },
      {
        step: 3,
        description: "Rebus air dengan gula merah hingga larut.",
        images: [],
      },
      {
        step: 4,
        description:
          "Masukkan cabai dan bawang putih ulek ke dalam air gula merah. Tambahkan air asam jawa dan kecap manis.",
        images: [],
      },
      {
        step: 5,
        description: "Beri garam, koreksi rasa. Masak sebentar hingga kuah mendidih.",
        images: [],
      },
      {
        step: 6,
        description: "Tata tahu goreng di mangkuk, siram dengan kuah gejrot. Sajikan hangat.",
        images: [],
      },
    ],
  },

  // MINUMAN INDONESIA (10 recipes)
  {
    id: 21,
    title: "Es Cendol",
    category: "minuman",
    author: {
      name: "Ibu Cendol",
      username: "@ibucendol",
      location: "Bandung",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Es cendol dengan santan dan gula merah yang manis segar",
    image: "/es-cendol.jpg",
    prepTime: "30 menit",
    cookTime: "20 menit",
    totalTime: "50 menit",
    servings: 6,
    cooksnaps: 445,
    saves: 734,
    reactions: {
      hungry: 223,
      love: 334,
      applause: 167,
    },
    ingredients: [
      { item: "100 gram tepung hunkwe", category: "Cendol" },
      { item: "600 ml air", category: "Cendol" },
      { item: "2 tetes pasta pandan", category: "Cendol" },
      { item: "1/4 sdt garam", category: "Cendol" },
      { item: "200 gram gula merah sisir", category: "Kuah" },
      { item: "200 ml air", category: "Kuah" },
      { item: "300 ml santan kental", category: "Pelengkap" },
      { item: "1/4 sdt garam", category: "Pelengkap" },
      { item: "Es batu secukupnya", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description:
          "Campurkan tepung hunkwe, air, pasta pandan, dan garam. Masak sambil diaduk hingga matang dan mengental.",
        images: [],
      },
      {
        step: 2,
        description:
          "Saring adonan cendol ke dalam wadah berisi air es menggunakan cetakan cendol atau saringan berlubang.",
        images: [],
      },
      {
        step: 3,
        description: "Rebus gula merah dengan air hingga larut dan mendidih. Saring dan dinginkan.",
        images: [],
      },
      {
        step: 4,
        description: "Rebus santan dengan sedikit garam hingga mendidih. Dinginkan.",
        images: [],
      },
      {
        step: 5,
        description: "Siapkan gelas saji, masukkan cendol, es batu, siram dengan kuah gula merah dan santan.",
        images: [],
      },
      {
        step: 6,
        description: "Es cendol siap disajikan.",
        images: [],
      },
    ],
  },
  {
    id: 22,
    title: "Wedang Jahe",
    category: "minuman",
    author: {
      name: "Mbak Wedang",
      username: "@mbakwedang",
      location: "Yogyakarta",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Wedang jahe hangat yang menyegarkan dan menghangatkan badan",
    image: "/wedang-jahe.jpg",
    prepTime: "10 menit",
    cookTime: "20 menit",
    totalTime: "30 menit",
    servings: 4,
    cooksnaps: 278,
    saves: 489,
    reactions: {
      hungry: 156,
      love: 223,
      applause: 112,
    },
    ingredients: [
      { item: "200 gram jahe, memarkan", category: "Bahan Utama" },
      { item: "1 liter air", category: "Bahan Utama" },
      { item: "150 gram gula merah sisir", category: "Pemanis" },
      { item: "3 batang serai, memarkan", category: "Bumbu" },
      { item: "3 lembar daun pandan", category: "Bumbu" },
      { item: "2 batang kayu manis", category: "Bumbu" },
    ],
    instructions: [
      {
        step: 1,
        description: "Bakar jahe hingga harum, lalu memarkan.",
        images: [],
      },
      {
        step: 2,
        description: "Rebus air dengan jahe, serai, daun pandan, dan kayu manis hingga mendidih.",
        images: [],
      },
      {
        step: 3,
        description: "Masukkan gula merah, masak hingga larut.",
        images: [],
      },
      {
        step: 4,
        description: "Kecilkan api, terus masak selama 15 menit agar rempah meresap.",
        images: [],
      },
      {
        step: 5,
        description: "Saring wedang jahe ke dalam gelas saji.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan wedang jahe hangat.",
        images: [],
      },
    ],
  },
  {
    id: 23,
    title: "Es Teler",
    category: "minuman",
    author: {
      name: "Pak Teler",
      username: "@pakteler",
      location: "Jakarta",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Es teler dengan berbagai buah segar, kelapa muda, dan santan",
    image: "/es-teler.jpg",
    prepTime: "25 menit",
    cookTime: "10 menit",
    totalTime: "35 menit",
    servings: 5,
    cooksnaps: 512,
    saves: 823,
    reactions: {
      hungry: 267,
      love: 378,
      applause: 189,
    },
    ingredients: [
      { item: "1 buah alpukat, potong dadu", category: "Buah" },
      { item: "1 buah nangka matang, potong", category: "Buah" },
      { item: "200 gram kelapa muda, keruk", category: "Buah" },
      { item: "100 gram cincau hitam, potong dadu", category: "Buah" },
      { item: "300 ml santan kental", category: "Kuah" },
      { item: "150 ml susu kental manis", category: "Kuah" },
      { item: "3 sdm sirup cocopandan", category: "Kuah" },
      { item: "Es serut secukupnya", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus santan hingga mendidih, dinginkan.",
        images: [],
      },
      {
        step: 2,
        description: "Campurkan santan dingin dengan susu kental manis dan sirup cocopandan.",
        images: [],
      },
      {
        step: 3,
        description: "Tata alpukat, nangka, kelapa muda, dan cincau di gelas saji.",
        images: [],
      },
      {
        step: 4,
        description: "Tambahkan es serut hingga penuh.",
        images: [],
      },
      {
        step: 5,
        description: "Siram dengan kuah santan.",
        images: [],
      },
      {
        step: 6,
        description: "Es teler siap disajikan.",
        images: [],
      },
    ],
  },
  {
    id: 24,
    title: "Bajigur",
    category: "minuman",
    author: {
      name: "Kang Bajigur",
      username: "@kangbajigur",
      location: "Bandung",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Minuman hangat khas Sunda dengan santan dan gula merah",
    image: "/bajigur.jpg",
    prepTime: "10 menit",
    cookTime: "20 menit",
    totalTime: "30 menit",
    servings: 4,
    cooksnaps: 334,
    saves: 556,
    reactions: {
      hungry: 178,
      love: 245,
      applause: 123,
    },
    ingredients: [
      { item: "500 ml santan dari 1/2 butir kelapa", category: "Bahan Utama" },
      { item: "200 gram gula merah sisir", category: "Pemanis" },
      { item: "3 cm jahe, memarkan", category: "Bumbu" },
      { item: "2 lembar daun pandan", category: "Bumbu" },
      { item: "1/4 sdt garam", category: "Bumbu" },
      { item: "100 gram kolang kaling, iris", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus santan dengan jahe, daun pandan, dan garam hingga mendidih sambil terus diaduk.",
        images: [],
      },
      {
        step: 2,
        description: "Tambahkan gula merah, masak hingga larut.",
        images: [],
      },
      {
        step: 3,
        description: "Kecilkan api, terus masak selama 10 menit.",
        images: [],
      },
      {
        step: 4,
        description: "Masukkan kolang kaling, masak sebentar.",
        images: [],
      },
      {
        step: 5,
        description: "Angkat dan saring bajigur.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan bajigur hangat.",
        images: [],
      },
    ],
  },
  {
    id: 25,
    title: "Es Campur",
    category: "minuman",
    author: {
      name: "Mak Campur",
      username: "@makcampur",
      location: "Surabaya",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Es campur dengan berbagai topping dan sirup yang manis segar",
    image: "/es-campur.jpg",
    prepTime: "20 menit",
    cookTime: "15 menit",
    totalTime: "35 menit",
    servings: 4,
    cooksnaps: 467,
    saves: 723,
    reactions: {
      hungry: 234,
      love: 345,
      applause: 167,
    },
    ingredients: [
      { item: "100 gram cincau hitam, potong dadu", category: "Topping" },
      { item: "100 gram nata de coco", category: "Topping" },
      { item: "100 gram kolang kaling, iris", category: "Topping" },
      { item: "3 buah pisang raja, potong", category: "Topping" },
      { item: "100 gram agar-agar, potong", category: "Topping" },
      { item: "200 ml santan kental", category: "Kuah" },
      { item: "100 ml susu kental manis", category: "Kuah" },
      { item: "3 sdm sirup merah", category: "Kuah" },
      { item: "Es serut secukupnya", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Rebus santan hingga mendidih, dinginkan.",
        images: [],
      },
      {
        step: 2,
        description: "Campurkan santan dengan susu kental manis.",
        images: [],
      },
      {
        step: 3,
        description: "Tata semua topping (cincau, nata de coco, kolang kaling, pisang, agar-agar) di gelas saji.",
        images: [],
      },
      {
        step: 4,
        description: "Tambahkan es serut hingga penuh.",
        images: [],
      },
      {
        step: 5,
        description: "Siram dengan kuah santan dan sirup merah.",
        images: [],
      },
      {
        step: 6,
        description: "Es campur siap disajikan.",
        images: [],
      },
    ],
  },
  {
    id: 26,
    title: "Bandrek",
    category: "minuman",
    author: {
      name: "Bi Bandrek",
      username: "@bibandrek",
      location: "Garut",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Minuman hangat dari jahe dengan aroma rempah yang khas",
    image: "/bandrek.jpg",
    prepTime: "10 menit",
    cookTime: "25 menit",
    totalTime: "35 menit",
    servings: 5,
    cooksnaps: 312,
    saves: 523,
    reactions: {
      hungry: 167,
      love: 234,
      applause: 112,
    },
    ingredients: [
      { item: "150 gram jahe, memarkan", category: "Bahan Utama" },
      { item: "1 liter air", category: "Bahan Utama" },
      { item: "200 gram gula merah sisir", category: "Pemanis" },
      { item: "3 batang serai, memarkan", category: "Bumbu" },
      { item: "3 lembar daun pandan", category: "Bumbu" },
      { item: "2 batang kayu manis", category: "Bumbu" },
      { item: "5 butir cengkeh", category: "Bumbu" },
      { item: "1 buah pala, memarkan", category: "Bumbu" },
      { item: "100 gram kolang kaling", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Bakar jahe hingga harum, lalu memarkan.",
        images: [],
      },
      {
        step: 2,
        description: "Rebus air dengan semua bumbu (jahe, serai, pandan, kayu manis, cengkeh, pala) hingga mendidih.",
        images: [],
      },
      {
        step: 3,
        description: "Masukkan gula merah, masak hingga larut.",
        images: [],
      },
      {
        step: 4,
        description: "Kecilkan api, masak selama 20 menit agar rempah meresap sempurna.",
        images: [],
      },
      {
        step: 5,
        description: "Masukkan kolang kaling, masak sebentar.",
        images: [],
      },
      {
        step: 6,
        description: "Saring bandrek dan sajikan hangat.",
        images: [],
      },
    ],
  },
  {
    id: 27,
    title: "Es Kelapa Muda",
    category: "minuman",
    author: {
      name: "Pak Kelapa",
      username: "@pakkelapa",
      location: "Bali",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Air kelapa muda segar yang menyegarkan dengan tambahan es",
    image: "/es-kelapa-muda.jpg",
    prepTime: "15 menit",
    cookTime: "0 menit",
    totalTime: "15 menit",
    servings: 4,
    cooksnaps: 578,
    saves: 912,
    reactions: {
      hungry: 289,
      love: 423,
      applause: 198,
    },
    ingredients: [
      { item: "4 buah kelapa muda", category: "Bahan Utama" },
      { item: "4 sdm sirup cocopandan", category: "Pemanis" },
      { item: "4 sdm susu kental manis", category: "Pelengkap" },
      { item: "Es batu secukupnya", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Buka kelapa muda, tuang air kelapa ke dalam gelas.",
        images: [],
      },
      {
        step: 2,
        description: "Keruk daging kelapa muda menggunakan sendok.",
        images: [],
      },
      {
        step: 3,
        description: "Masukkan daging kelapa ke dalam gelas berisi air kelapa.",
        images: [],
      },
      {
        step: 4,
        description: "Tambahkan sirup cocopandan dan susu kental manis.",
        images: [],
      },
      {
        step: 5,
        description: "Masukkan es batu secukupnya.",
        images: [],
      },
      {
        step: 6,
        description: "Aduk rata dan sajikan.",
        images: [],
      },
    ],
  },
  {
    id: 28,
    title: "Sekoteng",
    category: "minuman",
    author: {
      name: "Mas Koteng",
      username: "@maskoteng",
      location: "Semarang",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Minuman hangat dengan kuah jahe manis dan berbagai isian",
    image: "/sekoteng.jpg",
    prepTime: "15 menit",
    cookTime: "20 menit",
    totalTime: "35 menit",
    servings: 4,
    cooksnaps: 289,
    saves: 478,
    reactions: {
      hungry: 156,
      love: 212,
      applause: 98,
    },
    ingredients: [
      { item: "100 gram kacang tanah rebus", category: "Isian" },
      { item: "100 gram kolang kaling", category: "Isian" },
      { item: "100 gram pacar cina", category: "Isian" },
      { item: "50 gram kacang hijau rebus", category: "Isian" },
      { item: "100 gram jahe, memarkan", category: "Kuah" },
      { item: "1 liter air", category: "Kuah" },
      { item: "150 gram gula pasir", category: "Kuah" },
      { item: "2 lembar daun pandan", category: "Kuah" },
    ],
    instructions: [
      {
        step: 1,
        description: "Bakar jahe hingga harum, lalu memarkan.",
        images: [],
      },
      {
        step: 2,
        description: "Rebus air dengan jahe dan daun pandan hingga mendidih.",
        images: [],
      },
      {
        step: 3,
        description: "Masukkan gula pasir, masak hingga larut. Masak selama 15 menit.",
        images: [],
      },
      {
        step: 4,
        description: "Tata semua isian (kacang tanah, kolang kaling, pacar cina, kacang hijau) di mangkuk saji.",
        images: [],
      },
      {
        step: 5,
        description: "Siram dengan kuah jahe panas.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan sekoteng hangat.",
        images: [],
      },
    ],
  },
  {
    id: 29,
    title: "Es Dawet Ayu",
    category: "minuman",
    author: {
      name: "Yu Dawet",
      username: "@yudawet",
      location: "Banjarnegara",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Dawet hijau dengan kuah santan dan gula merah yang manis legit",
    image: "/es-dawet-ayu.jpg",
    prepTime: "30 menit",
    cookTime: "20 menit",
    totalTime: "50 menit",
    servings: 6,
    cooksnaps: 401,
    saves: 689,
    reactions: {
      hungry: 212,
      love: 312,
      applause: 145,
    },
    ingredients: [
      { item: "100 gram tepung beras", category: "Dawet" },
      { item: "50 gram tepung sagu", category: "Dawet" },
      { item: "600 ml air daun pandan", category: "Dawet" },
      { item: "1/4 sdt garam", category: "Dawet" },
      { item: "200 gram gula merah sisir", category: "Kuah" },
      { item: "150 ml air", category: "Kuah" },
      { item: "300 ml santan kental", category: "Pelengkap" },
      { item: "1/4 sdt garam", category: "Pelengkap" },
      { item: "Es batu secukupnya", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description:
          "Campurkan tepung beras, tepung sagu, air daun pandan, dan garam. Masak sambil diaduk hingga matang.",
        images: [],
      },
      {
        step: 2,
        description: "Saring adonan dawet ke dalam wadah berisi air es menggunakan cetakan dawet.",
        images: [],
      },
      {
        step: 3,
        description: "Rebus gula merah dengan air hingga larut. Saring dan dinginkan.",
        images: [],
      },
      {
        step: 4,
        description: "Rebus santan dengan garam hingga mendidih. Dinginkan.",
        images: [],
      },
      {
        step: 5,
        description: "Siapkan gelas, masukkan dawet, es batu, siram dengan kuah gula merah dan santan.",
        images: [],
      },
      {
        step: 6,
        description: "Es dawet ayu siap disajikan.",
        images: [],
      },
    ],
  },
  {
    id: 30,
    title: "Kopi Susu Gula Aren",
    category: "minuman",
    author: {
      name: "Barista Nusantara",
      username: "@baristanusantara",
      location: "Makassar",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Kopi susu dengan gula aren yang manis legit khas Indonesia",
    image: "/kopi-susu-gula-aren.jpg",
    prepTime: "10 menit",
    cookTime: "15 menit",
    totalTime: "25 menit",
    servings: 2,
    cooksnaps: 534,
    saves: 867,
    reactions: {
      hungry: 278,
      love: 401,
      applause: 189,
    },
    ingredients: [
      { item: "4 sdm bubuk kopi robusta", category: "Bahan Utama" },
      { item: "300 ml air panas", category: "Bahan Utama" },
      { item: "100 gram gula aren, sisir", category: "Pemanis" },
      { item: "100 ml air", category: "Pemanis" },
      { item: "200 ml susu cair full cream", category: "Pelengkap" },
      { item: "Es batu secukupnya", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Seduh bubuk kopi dengan air panas, diamkan 5 menit. Saring.",
        images: [],
      },
      {
        step: 2,
        description: "Rebus gula aren dengan air hingga larut dan sedikit kental. Dinginkan.",
        images: [],
      },
      {
        step: 3,
        description: "Siapkan gelas, masukkan es batu.",
        images: [],
      },
      {
        step: 4,
        description: "Tuang sirup gula aren secukupnya ke dalam gelas.",
        images: [],
      },
      {
        step: 5,
        description: "Tuang susu cair, lalu tuang kopi hitam perlahan.",
        images: [],
      },
      {
        step: 6,
        description: "Aduk rata sebelum diminum.",
        images: [],
      },
    ],
  },

  // JAJANAN INDONESIA (5 recipes)
  {
    id: 31,
    title: "Pisang Goreng Crispy",
    category: "jajanan",
    author: {
      name: "Tante Pisgor",
      username: "@tantepisgor",
      location: "Bogor",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Pisang goreng dengan balutan tepung crispy yang renyah",
    image: "/pisang-goreng-crispy.jpg",
    prepTime: "15 menit",
    cookTime: "20 menit",
    totalTime: "35 menit",
    servings: 10,
    cooksnaps: 623,
    saves: 945,
    reactions: {
      hungry: 312,
      love: 467,
      applause: 223,
    },
    ingredients: [
      { item: "10 buah pisang kepok, belah dua", category: "Bahan Utama" },
      { item: "200 gram tepung terigu", category: "Adonan" },
      { item: "50 gram tepung beras", category: "Adonan" },
      { item: "50 gram tepung maizena", category: "Adonan" },
      { item: "2 sdm gula pasir", category: "Adonan" },
      { item: "1/4 sdt garam", category: "Adonan" },
      { item: "1/2 sdt vanili", category: "Adonan" },
      { item: "200 ml air es", category: "Adonan" },
      { item: "Minyak untuk menggoreng", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Campurkan semua tepung, gula, garam, dan vanili.",
        images: [],
      },
      {
        step: 2,
        description: "Tuang air es sedikit demi sedikit sambil diaduk hingga adonan kental tapi cukup encer.",
        images: [],
      },
      {
        step: 3,
        description: "Celupkan pisang ke dalam adonan hingga terbalut rata.",
        images: [],
      },
      {
        step: 4,
        description: "Goreng pisang dengan api sedang hingga berwarna keemasan dan crispy.",
        images: [],
      },
      {
        step: 5,
        description: "Angkat dan tiriskan minyak.",
        images: [],
      },
      {
        step: 6,
        description: "Sajikan pisang goreng crispy hangat dengan teh atau kopi.",
        images: [],
      },
    ],
  },
  {
    id: 32,
    title: "Lemper Ayam",
    category: "jajanan",
    author: {
      name: "Ibu Lemper",
      username: "@ibulemper",
      location: "Jakarta",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Ketan isi ayam suwir berbumbu yang dibungkus daun pisang",
    image: "/lemper-ayam.jpg",
    prepTime: "40 menit",
    cookTime: "45 menit",
    totalTime: "1 jam 25 menit",
    servings: 15,
    cooksnaps: 456,
    saves: 723,
    reactions: {
      hungry: 234,
      love: 345,
      applause: 167,
    },
    ingredients: [
      { item: "500 gram beras ketan putih, rendam 2 jam", category: "Bahan Utama" },
      { item: "400 ml santan kental", category: "Bahan Utama" },
      { item: "2 lembar daun pandan", category: "Bahan Utama" },
      { item: "1 sdt garam", category: "Bahan Utama" },
      { item: "300 gram daging ayam fillet", category: "Isian" },
      { item: "5 siung bawang putih, cincang", category: "Isian" },
      { item: "3 siung bawang merah, cincang", category: "Isian" },
      { item: "2 cm lengkuas, memarkan", category: "Isian" },
      { item: "1 batang serai, memarkan", category: "Isian" },
      { item: "2 sdm kecap manis", category: "Isian" },
      { item: "Garam dan gula secukupnya", category: "Isian" },
      { item: "Daun pisang untuk membungkus", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description:
          "Masak beras ketan dengan santan, daun pandan, dan garam hingga matang dan pulen. Dinginkan sedikit.",
        images: [],
      },
      {
        step: 2,
        description: "Rebus ayam hingga matang, suwir-suwir halus.",
        images: [],
      },
      {
        step: 3,
        description: "Tumis bawang putih dan bawang merah hingga harum. Masukkan lengkuas dan serai.",
        images: [],
      },
      {
        step: 4,
        description: "Masukkan ayam suwir, kecap manis, garam, dan gula. Masak hingga bumbu meresap dan kering.",
        images: [],
      },
      {
        step: 5,
        description:
          "Ambil sedikit ketan, pipihkan di atas daun pisang. Beri isian ayam, bentuk memanjang dan bungkus rapat.",
        images: [],
      },
      {
        step: 6,
        description: "Kukus lemper selama 15 menit. Sajikan hangat atau dingin.",
        images: [],
      },
    ],
  },
  {
    id: 33,
    title: "Risoles Mayo",
    category: "jajanan",
    author: {
      name: "Mbak Risol",
      username: "@mbakrisol",
      location: "Bandung",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Risoles dengan isian ragout dan mayones yang creamy",
    image: "/risoles-mayo.jpg",
    prepTime: "50 menit",
    cookTime: "40 menit",
    totalTime: "1 jam 30 menit",
    servings: 20,
    cooksnaps: 534,
    saves: 834,
    reactions: {
      hungry: 267,
      love: 389,
      applause: 178,
    },
    ingredients: [
      { item: "200 gram tepung terigu", category: "Kulit" },
      { item: "2 butir telur", category: "Kulit" },
      { item: "400 ml susu cair", category: "Kulit" },
      { item: "2 sdm margarin, lelehkan", category: "Kulit" },
      { item: "1/4 sdt garam", category: "Kulit" },
      { item: "200 gram daging ayam cincang", category: "Isian" },
      { item: "100 gram wortel, potong dadu kecil", category: "Isian" },
      { item: "50 gram buncis, iris", category: "Isian" },
      { item: "3 sdm tepung terigu", category: "Isian" },
      { item: "200 ml susu cair", category: "Isian" },
      { item: "3 sdm mayones", category: "Isian" },
      { item: "3 siung bawang putih, cincang", category: "Isian" },
      { item: "Garam, merica, pala bubuk", category: "Isian" },
      { item: "Tepung panir untuk coating", category: "Pelengkap" },
    ],
    instructions: [
      {
        step: 1,
        description: "Untuk kulit: campur tepung, telur, susu, margarin, dan garam. Buat dadar tipis di teflon.",
        images: [],
      },
      {
        step: 2,
        description: "Tumis bawang putih, masukkan ayam cincang hingga berubah warna.",
        images: [],
      },
      {
        step: 3,
        description: "Masukkan wortel dan buncis, masak sebentar. Taburi tepung terigu, aduk rata.",
        images: [],
      },
      {
        step: 4,
        description:
          "Tuang susu cair sambil diaduk hingga mengental. Tambahkan mayones, garam, merica, dan pala. Dinginkan.",
        images: [],
      },
      {
        step: 5,
        description:
          "Ambil kulit risoles, beri isian, lipat dan gulung rapat. Celupkan ke kocokan telur lalu balut tepung panir.",
        images: [],
      },
      {
        step: 6,
        description: "Goreng risoles hingga berwarna keemasan. Sajikan hangat.",
        images: [],
      },
    ],
  },
  {
    id: 34,
    title: "Klepon",
    category: "jajanan",
    author: {
      name: "Nenek Klepon",
      username: "@nenekklepon",
      location: "Solo",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Kue klepon dengan isian gula merah dan taburan kelapa parut",
    image: "/klepon.jpg",
    prepTime: "30 menit",
    cookTime: "20 menit",
    totalTime: "50 menit",
    servings: 20,
    cooksnaps: 489,
    saves: 756,
    reactions: {
      hungry: 245,
      love: 356,
      applause: 167,
    },
    ingredients: [
      { item: "250 gram tepung ketan", category: "Bahan Utama" },
      { item: "150 ml air daun pandan", category: "Bahan Utama" },
      { item: "1/4 sdt garam", category: "Bahan Utama" },
      { item: "100 gram gula merah, sisir halus", category: "Isian" },
      { item: "150 gram kelapa parut", category: "Taburan" },
      { item: "1/4 sdt garam", category: "Taburan" },
      { item: "1 lembar daun pandan", category: "Taburan" },
    ],
    instructions: [
      {
        step: 1,
        description: "Campurkan tepung ketan dengan air daun pandan dan garam, uleni hingga kalis.",
        images: [],
      },
      {
        step: 2,
        description: "Ambil sedikit adonan, pipihkan, beri isian gula merah, bentuk bulat.",
        images: [],
      },
      {
        step: 3,
        description: "Rebus air hingga mendidih, masukkan klepon. Masak hingga klepon mengapung.",
        images: [],
      },
      {
        step: 4,
        description: "Angkat klepon, tiriskan.",
        images: [],
      },
      {
        step: 5,
        description: "Kukus kelapa parut dengan garam dan daun pandan selama 10 menit.",
        images: [],
      },
      {
        step: 6,
        description: "Gulingkan klepon di kelapa parut. Sajikan.",
        images: [],
      },
    ],
  },
  {
    id: 35,
    title: "Martabak Manis",
    category: "jajanan",
    author: {
      name: "Abang Terang Bulan",
      username: "@abangterangbulan",
      location: "Medan",
      avatar: "/placeholder.svg?height=48&width=48",
    },
    description: "Martabak manis dengan berbagai topping yang manis dan lezat",
    image: "/martabak-manis.jpg",
    prepTime: "2 jam",
    cookTime: "30 menit",
    totalTime: "2 jam 30 menit",
    servings: 4,
    cooksnaps: 678,
    saves: 1023,
    reactions: {
      hungry: 345,
      love: 512,
      applause: 234,
    },
    ingredients: [
      { item: "250 gram tepung terigu protein sedang", category: "Adonan" },
      { item: "2 butir telur", category: "Adonan" },
      { item: "50 gram gula pasir", category: "Adonan" },
      { item: "1 sdt ragi instan", category: "Adonan" },
      { item: "1/2 sdt baking powder", category: "Adonan" },
      { item: "1/4 sdt baking soda", category: "Adonan" },
      { item: "300 ml susu cair hangat", category: "Adonan" },
      { item: "2 sdm margarin, lelehkan", category: "Adonan" },
      { item: "Margarin untuk olesan", category: "Topping" },
      { item: "Susu kental manis", category: "Topping" },
      { item: "Cokelat meses, kacang, keju", category: "Topping" },
    ],
    instructions: [
      {
        step: 1,
        description: "Campurkan tepung, gula, ragi, baking powder, dan baking soda.",
        images: [],
      },
      {
        step: 2,
        description:
          "Tambahkan telur dan susu hangat, aduk rata. Masukkan margarin leleh. Diamkan adonan hingga mengembang, sekitar 1.5 jam.",
        images: [],
      },
      {
        step: 3,
        description: "Panaskan loyang martabak, olesi margarin.",
        images: [],
      },
      {
        step: 4,
        description: "Tuang adonan, tutup loyang, masak dengan api kecil hingga berlubang dan matang.",
        images: [],
      },
      {
        step: 5,
        description: "Angkat martabak, olesi dengan margarin dan susu kental manis.",
        images: [],
      },
      {
        step: 6,
        description: "Taburi dengan topping sesuai selera (cokelat, kacang, keju). Lipat dan potong. Sajikan.",
        images: [],
      },
    ],
  },
]

export function getAllRecipes(): Recipe[] {
  return recipes
}

export function getRecipeById(id: number): Recipe | undefined {
  return recipes.find((recipe) => recipe.id === id)
}

export function getRecipesByCategory(category: "makanan" | "minuman" | "jajanan"): Recipe[] {
  return recipes.filter((recipe) => recipe.category === category)
}

export function searchRecipes(query: string): Recipe[] {
  const lowercaseQuery = query.toLowerCase()
  return recipes.filter(
    (recipe) =>
      recipe.title.toLowerCase().includes(lowercaseQuery) ||
      recipe.description.toLowerCase().includes(lowercaseQuery) ||
      recipe.ingredients.some((ing) => ing.item.toLowerCase().includes(lowercaseQuery)),
  )
}
